### ISSUE TITLE
would it be possible to add a description of the FAIRness score somewhere?

### ISSUE THREAD

**Issue by mariegosme** [euraf/AF-tools-database#7]
Hello,
answering to an issue (https://github.com/euraf/agroforestreeadvice/issues/19) of AgroforesTreeAdvice, I wanted to point to the way the FAIRness score is computedn and couldn't find it on github. Would it be possible to add a description of the FAIRness score (based on milestone 16 of DigitAF) somewhere?
Thank you in advance

**Comment by palmajoao** [comment]
Hi @mariegosme 
Thanks for pointing that out. Very timely because we had a internal discussion last week and we are on it already: 
1) Adapting the milestone report in a document to describe the FAIRness score and 
2) Actually make a simple tool for FAIRness self-assessment of a particular tool (e.g. to know in advance the score before uploading the tool). Will close this issue when both report and tool are ready

**Comment by palmajoao** [comment]
Hi @mariegosme 

You can find the code to calculate the FAIRness score in this repo: https://github.com/euraf/AF_FAIRness

More specifically in this code:: https://github.com/euraf/AF_FAIRness/blob/main/catalogue/tools/scoring/tools_fairness_scoring.js

Similarly you can find the Data fairness scoring here: 
https://github.com/euraf/AF_FAIRness/blob/main/catalogue/data/scoring/data_fairness_scoring.js

you can now test the FAIRness of your tools or data previously to submit to the catalogues.
The code is availabe in the[ same repository](https://github.com/euraf/AF_FAIRness), and you can find the implementation in  https://digitaf.eu/tools-and-data-catalogue/

Finally, this repo will be deprecated as we are merging the Data and Tools into this [single code repository](https://github.com/euraf/AF_FAIRness).
